build:
  environment:
    php: "8.2"
  services:
    mysql: 5.7
    redis: 7
  dependencies:
    override:
      - composer self-update --2
      - composer install --no-interaction --prefer-dist
  tests:
    before:
      - printf 'DB_HOST=127.0.0.1\nDB_USER=ansilume\nDB_PASSWORD=secret\nDB_NAME=ansilume\nDB_TEST_NAME=ansilume_test\nREDIS_HOST=127.0.0.1\n' > .env
      - mysql -u root -h 127.0.0.1 -e "CREATE DATABASE ansilume; CREATE DATABASE ansilume_test; CREATE USER 'ansilume'@'%' IDENTIFIED BY 'secret'; GRANT ALL ON ansilume.* TO 'ansilume'@'%'; GRANT ALL ON ansilume_test.* TO 'ansilume'@'%'; FLUSH PRIVILEGES;"
      - php yii migrate --interactive=0
      - sed -i 's/DB_NAME=ansilume/DB_NAME=ansilume_test/' .env && php yii migrate --interactive=0 && sed -i 's/DB_NAME=ansilume_test/DB_NAME=ansilume/' .env
    override:
      - php-scrutinizer-run
      -
        command: vendor/bin/phpunit --testsuite=Unit --colors=never
        coverage:
          file: clover.xml
          format: php-clover

checks:
  php:
    code_rating: true
    duplication: true

tools:
  php_code_sniffer:
    config:
      standard: PSR12
  php_mess_detector: true
  php_cpd: true

filter:
  excluded_paths:
    - vendor/*
    - tests/*
    - runtime/*
    - web/assets/*
    - web/js/cronstrue.min.js
    - docker/*
    - migrations/*
