<?php

declare(strict_types=1);

namespace app\tests\integration\commands;

use app\commands\E2eTeamScopingSeeder;
use app\models\JobTemplate;
use app\models\User;
use app\services\ProjectAccessChecker;
use app\tests\integration\DbTestCase;

/**
 * The team scoping fixtures of the E2E specs (E2eTeamScopingSeeder).
 *
 * e2e-alpha-viewed-tmpl, a template whose project team-alpha (with
 * e2e-operator) may only view, has a trigger token that runs as the seeding
 * user, so tests/e2e/tests/team-scoping/triggers.spec.ts can check that the
 * operator is not told whom the trigger runs as. The test database holds no
 * "e2e-" rows outside a test, and the rollback removes them.
 */
class E2eTeamScopingSeederTest extends DbTestCase
{
    private const VIEWED = 'e2e-alpha-viewed-tmpl';

    private int $adminId;
    private int $operatorId;

    /** @var list<string> */
    private array $log = [];

    protected function setUp(): void
    {
        parent::setUp();
        $admin = $this->createUser('admin');
        $admin->is_superadmin = true;
        $admin->save(false);
        $this->adminId = (int)$admin->id;
        $this->operatorId = (int)$this->namedUser('e2e-operator', 'operator')->id;
        $this->namedUser('e2e-viewer', 'viewer');
        $this->log = [];
    }

    public function testTheTemplateTheOperatorMayOnlyViewHasATriggerTokenThatRunsAsTheSeedingUser(): void
    {
        $this->seed();

        $viewed = $this->template(self::VIEWED);
        $this->assertTrue($viewed->hasTriggerToken());
        $this->assertSame($this->adminId, $viewed->trigger_token_created_by);
        $this->assertSame($this->adminId, $viewed->getTriggerUserId());
        $checker = \Yii::$app->get('projectAccessChecker');
        $this->assertInstanceOf(ProjectAccessChecker::class, $checker);
        $this->assertTrue($checker->canViewChildResource($this->operatorId, (int)$viewed->project_id));
        $this->assertFalse($checker->canOperateChildResource($this->operatorId, (int)$viewed->project_id));

        $own = $this->template('e2e-alpha-tmpl');
        $this->assertTrue($checker->canOperateChildResource($this->operatorId, (int)$own->project_id));
        $this->assertFalse($own->hasTriggerToken(), 'only the viewed template gets a token');
    }

    public function testSeedingAgainKeepsTheToken(): void
    {
        $this->seed();
        $token = $this->template(self::VIEWED)->trigger_token;

        $this->seed();

        $this->assertContains("  Team scoping data already exists.\n", $this->log);
        $this->assertSame(1, (int)JobTemplate::find()->where(['name' => self::VIEWED])->count());
        $this->assertSame($token, $this->template(self::VIEWED)->trigger_token);
    }

    /**
     * @return array<string, array{0: bool}>
     */
    public static function changedTokenProvider(): array
    {
        return [
            'revoked' => [false],
            'generated by another user' => [true],
        ];
    }

    /**
     * @dataProvider changedTokenProvider
     */
    public function testSeedingAgainRestoresATokenThatRunsAsTheSeedingUser(bool $regenerated): void
    {
        $this->seed();
        $viewed = $this->template(self::VIEWED);
        if ($regenerated) {
            $viewed->generateTriggerToken($this->operatorId);
        } else {
            $viewed->revokeTriggerToken();
        }

        $this->seed();

        $restored = $this->template(self::VIEWED);
        $this->assertTrue($restored->hasTriggerToken());
        $this->assertSame($this->adminId, $restored->trigger_token_created_by);
    }

    public function testSeedingAgainWithoutTheViewedTemplateAddsNoToken(): void
    {
        $this->seed();
        $this->template(self::VIEWED)->softDelete();

        $this->seed();

        $this->assertNull(JobTemplate::findOne(['name' => self::VIEWED]), 'the deleted template stays deleted');
        $deleted = JobTemplate::findWithDeleted()->where(['name' => self::VIEWED])->one();
        $this->assertInstanceOf(JobTemplate::class, $deleted);
        $this->assertFalse($deleted->hasTriggerToken());
    }

    private function seed(): void
    {
        (new E2eTeamScopingSeeder(function (string $msg): void {
            $this->log[] = $msg;
        }))->seed($this->adminId, (int)$this->createRunnerGroup($this->adminId)->id);
    }

    private function namedUser(string $username, string $role): User
    {
        $user = $this->createUser($role);
        $user->username = $username;
        $user->save(false);
        $auth = \Yii::$app->authManager;
        $this->assertNotNull($auth);
        $rbacRole = $auth->getRole($role);
        $this->assertNotNull($rbacRole, "RBAC role {$role}");
        $auth->assign($rbacRole, (int)$user->id);

        return $user;
    }

    private function template(string $name): JobTemplate
    {
        $template = JobTemplate::findOne(['name' => $name]);
        $this->assertNotNull($template, $name);

        return $template;
    }
}
