<?php

declare(strict_types=1);

namespace app\tests\unit\components\vault;

use app\components\vault\VaultEnvelope;
use PHPUnit\Framework\TestCase;

/**
 * The fixtures were generated by ansible-vault and cross-checked against it
 * (tests/fixtures/vault/README.md), so these tests pin Ansible's behaviour.
 */
class VaultEnvelopeTest extends TestCase
{
    use TemporaryTree;

    private const DEV = 'ansilume-test-dummy-dev';
    private const PROD = 'ansilume-test-dummy-prod';

    public function testParsesAFormat11FileWithACustomSalt(): void
    {
        $envelope = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));

        $this->assertSame('1.1', $envelope->version);
        $this->assertNull($envelope->vaultId);
        // ANSIBLE_VAULT_ENCRYPT_SALT is used as the raw salt bytes, of any length.
        $this->assertSame('ansilume-fixture-1.1', $envelope->salt);
        $this->assertSame(32, strlen($envelope->hmac));
        $this->assertSame(32, strlen($envelope->ciphertext), 'PKCS7 pads the 29-byte plaintext to two blocks');
    }

    public function testParsesAFormat12FileWithItsVaultId(): void
    {
        $envelope = VaultEnvelope::parse(self::fixtureContent('file-1.2-prod.yml'));

        $this->assertSame('1.2', $envelope->version);
        $this->assertSame('prod', $envelope->vaultId);
        $this->assertSame('ansilume-fixture-1.2-prod', $envelope->salt);
    }

    public function testOnlyTheRightPasswordOpensAVault(): void
    {
        $dev = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));
        $prod = VaultEnvelope::parse(self::fixtureContent('file-1.2-prod.yml'));

        $this->assertTrue($dev->opens(self::DEV));
        $this->assertFalse($dev->opens(self::PROD));
        $this->assertFalse($dev->opens(self::DEV . 'x'));
        $this->assertTrue($prod->opens(self::PROD), 'the vault ID is a label, not part of the key');
        $this->assertFalse($prod->opens(self::DEV));
    }

    public function testEmptyAndBlankPasswordsNeverOpen(): void
    {
        $envelope = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));

        $this->assertFalse($envelope->opens(''));
        $this->assertFalse($envelope->opens(" \t\r\n\x0B\x0C"));
    }

    public function testPasswordsAreNormalisedLikeAnsiblePasswordFiles(): void
    {
        $envelope = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));

        // Regression guard: a password stored with a trailing newline must not
        // produce a false "does not open" warning.
        $this->assertTrue($envelope->opens(self::DEV . "\n"));
        $this->assertTrue($envelope->opens(" \t" . self::DEV . " \t\r\n\n"));
        $this->assertTrue($envelope->opens(self::DEV . "\x0C"), 'Python strips the form feed, PHP trim() does not');
        $this->assertTrue($envelope->opens("\x0B" . self::DEV));
        $this->assertFalse($envelope->opens('ansilume-test-dummy dev'), 'inner whitespace stays');
    }

    public function testNormalizePasswordStripsPythonWhitespaceOnly(): void
    {
        $this->assertSame('secret', VaultEnvelope::normalizePassword(" \t\n\r\x0B\x0Csecret\x0C\x0B\r\n\t "));
        $this->assertSame("secret\0", VaultEnvelope::normalizePassword("secret\0"), 'Python keeps NUL, PHP trim() would strip it');
        $this->assertSame("\0secret", VaultEnvelope::normalizePassword("\0secret"));
        $this->assertSame('se cret', VaultEnvelope::normalizePassword(' se cret '));
        $this->assertSame('', VaultEnvelope::normalizePassword(" \n "));
    }

    public function testTheFingerprintIdentifiesTheEncryptedContent(): void
    {
        $dev = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));
        $prod = VaultEnvelope::parse(self::fixtureContent('file-1.2-prod.yml'));

        $this->assertSame(hash('sha256', $dev->salt . $dev->hmac . $dev->ciphertext), $dev->fingerprint());
        $this->assertMatchesRegularExpression('/^[0-9a-f]{64}$/', $dev->fingerprint());
        $this->assertNotSame($dev->fingerprint(), $prod->fingerprint());
    }

    /**
     * @return array<string, array{0: callable(string): string}>
     */
    public static function acceptedVariantProvider(): array
    {
        return [
            'CRLF line endings' => [static fn (string $text): string => str_replace("\n", "\r\n", $text)],
            'CR line endings' => [static fn (string $text): string => str_replace("\n", "\r", $text)],
            'no final newline' => [static fn (string $text): string => rtrim($text, "\n")],
            'body on one line' => [static fn (string $text): string => self::rewrap($text, PHP_INT_MAX)],
            'body wrapped at 64 columns' => [static fn (string $text): string => self::rewrap($text, 64)],
            'upper-case hex' => [static fn (string $text): string => strtoupper($text)],
            'whitespace around the header fields' => [static fn (string $text): string => "\$ANSIBLE_VAULT ; 1.1 ;\tAES256 \t" . strstr($text, "\n")],
            'empty lines in the body' => [static fn (string $text): string => str_replace("\n", "\n\n", $text)],
        ];
    }

    /**
     * @dataProvider acceptedVariantProvider
     * @param callable(string): string $variant
     */
    public function testAcceptsWhatAnsibleAccepts(callable $variant): void
    {
        $original = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));

        $envelope = VaultEnvelope::parse($variant(self::fixtureContent('file-1.1.yml')));

        $this->assertSame($original->fingerprint(), $envelope->fingerprint());
        $this->assertTrue($envelope->opens(self::DEV));
    }

    public function testAFourthHeaderFieldIsTheVaultIdWhateverTheVersion(): void
    {
        $body = self::bodyOf(self::fixtureContent('file-1.1.yml'));

        $this->assertSame('prod', VaultEnvelope::parse("\$ANSIBLE_VAULT;1.1;AES256;prod\n" . $body)->vaultId);
        $this->assertSame('prod', VaultEnvelope::parse("\$ANSIBLE_VAULT;1.2;AES256;prod;extra\n" . $body)->vaultId);
        $this->assertSame('', VaultEnvelope::parse("\$ANSIBLE_VAULT;1.2;AES256;\n" . $body)->vaultId, 'present but empty');
        $this->assertSame('9.9', VaultEnvelope::parse("\$ANSIBLE_VAULT;9.9;AES256\n" . $body)->version, 'Ansible never checks the version');
    }

    public function testAnEmptySaltOrCiphertextIsAcceptedLikeAnsibleDoes(): void
    {
        $envelope = VaultEnvelope::parse(self::sealed('pw', '', 'sixteen bytes!!!'));
        $this->assertSame('', $envelope->salt);
        $this->assertTrue($envelope->opens('pw'));

        $this->assertSame('', VaultEnvelope::parse(self::sealed('pw', 'salt', ''))->ciphertext);
    }

    public function testAHmacOfTheWrongLengthNeverOpens(): void
    {
        $valid = VaultEnvelope::parse(self::fixtureContent('file-1.1.yml'));

        $short = new VaultEnvelope('1.1', null, $valid->salt, substr($valid->hmac, 0, 31), $valid->ciphertext);

        $this->assertFalse($short->opens(self::DEV));
    }

    /**
     * @return array<string, array{0: string, 1: string}>
     */
    public static function malformedProvider(): array
    {
        $file = self::fixtureContent('file-1.1.yml');
        $body = self::bodyOf($file);
        [$salt, $hmac, $ciphertext] = explode("\n", (string)hex2bin(str_replace("\n", '', $body)), 3);

        return [
            'trailing whitespace on a body line' => [self::fixtureContent('malformed-trailing-space.yml'), 'the vault body has spaces or tabs, e.g. trailing whitespace on a line'],
            'byte order mark' => ["\xEF\xBB\xBF" . $file, 'ansible does not read it as vault data: it starts with a UTF-8 byte order mark'],
            'blank first line' => ["\n" . $file, 'ansible does not read it as vault data: there are blank lines or spaces before $ANSIBLE_VAULT'],
            'indented header' => ['  ' . $file, 'there are blank lines or spaces before $ANSIBLE_VAULT'],
            'empty' => ['', 'ansible does not read it as vault data: it is empty'],
            'only whitespace' => [" \n\t\n", 'it is empty'],
            'only a byte order mark' => ["\xEF\xBB\xBF", 'it is empty'],
            'not vault data' => ["db_password: plain\n", 'ansible does not read it as vault data: it does not start with $ANSIBLE_VAULT'],
            'header only' => ["\$ANSIBLE_VAULT;1.1;AES256\n", 'the vault has a header but no body'],
            'no cipher field' => ["\$ANSIBLE_VAULT;1.1\n" . $body, 'the vault header has no cipher field'],
            'old AES cipher' => ["\$ANSIBLE_VAULT;1.0;AES\n" . $body, 'unsupported cipher: ansible reads only AES256'],
            'non-ASCII vault id' => ["\$ANSIBLE_VAULT;1.2;AES256;pr\xC3\xB6d\n" . $body, 'ansible does not read it as vault data: the header has non-ASCII characters'],
            'folded YAML value' => [str_replace("\n", ' ', rtrim($file)) . "\n", 'the header and the body are on one line: a folded (>) YAML value loses the line breaks, use |'],
            'odd number of hex digits' => [substr(rtrim($file), 0, -1) . "\n", 'the vault body has an odd number of hex digits'],
            'non-hex body' => ["\$ANSIBLE_VAULT;1.1;AES256\n" . substr($body, 0, -3) . "zz\n", 'the vault body has characters that are not hex digits'],
            'body without three lines' => [self::envelopeOf($salt . "\n" . $hmac), 'the decoded vault body is not salt, HMAC and ciphertext'],
            'salt not hex' => [self::envelopeOf("zz\n{$hmac}\n{$ciphertext}"), 'the salt has characters that are not hex digits'],
            'salt with spaces' => [self::envelopeOf("61 62\n{$hmac}\n{$ciphertext}"), 'the salt has spaces or tabs'],
            'salt with an odd number of digits' => [self::envelopeOf("616\n{$hmac}\n{$ciphertext}"), 'the salt has an odd number of hex digits'],
            'HMAC not hex' => [self::envelopeOf("{$salt}\nxy\n{$ciphertext}"), 'the HMAC has characters that are not hex digits'],
            'HMAC too short' => [self::envelopeOf("{$salt}\nabcd\n{$ciphertext}"), 'the HMAC has 2 bytes instead of 32, no password opens it'],
            'ciphertext not hex' => [self::envelopeOf("{$salt}\n{$hmac}\n{$ciphertext}\n00"), 'the ciphertext has characters that are not hex digits'],
        ];
    }

    public function testErrorMessagesNeverQuoteFileContent(): void
    {
        $body = self::bodyOf(self::fixtureContent('file-1.1.yml'));

        try {
            VaultEnvelope::parse("\$ANSIBLE_VAULT;1.1;hunter2\n" . $body);
            $this->fail('accepted an unknown cipher');
        } catch (\UnexpectedValueException $e) {
            $this->assertStringNotContainsString('hunter2', $e->getMessage());
        }
    }

    /**
     * @dataProvider malformedProvider
     */
    public function testRejectsWhatAnsibleRejectsWithAReadableReason(string $text, string $reason): void
    {
        $this->expectException(\UnexpectedValueException::class);
        $this->expectExceptionMessage($reason);

        VaultEnvelope::parse($text);
    }

    /**
     * The body lines of a vault text, joined by newlines.
     */
    private static function bodyOf(string $text): string
    {
        $lines = explode("\n", trim($text));

        return implode("\n", array_slice($lines, 1)) . "\n";
    }

    private static function rewrap(string $text, int $width): string
    {
        $lines = explode("\n", trim($text));
        $hex = implode('', array_slice($lines, 1));

        return $lines[0] . "\n" . implode("\n", str_split($hex, min($width, strlen($hex)))) . "\n";
    }

    /**
     * A vault text whose body decodes to $inner (hex salt, HMAC and ciphertext lines).
     */
    private static function envelopeOf(string $inner): string
    {
        return "\$ANSIBLE_VAULT;1.1;AES256\n" . chunk_split(bin2hex($inner), 80, "\n");
    }

    /**
     * A vault built the way Ansible builds one, for shapes ansible-vault never
     * writes; the fixtures are the cross-check against Ansible itself.
     */
    private static function sealed(string $password, string $salt, string $ciphertext): string
    {
        $keys = (string)openssl_pbkdf2($password, $salt, 64, 10000, 'sha256');
        $hmac = hash_hmac('sha256', $ciphertext, substr($keys, 32), true);

        return self::envelopeOf(bin2hex($salt) . "\n" . bin2hex($hmac) . "\n" . bin2hex($ciphertext));
    }
}
